In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [18]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [22]:
df.PetalLengthCm

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

In [24]:
df.PetalLengthCm[0]

1.4

In [13]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [17]:
df.head(10) # Returns the first 10 rows

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [19]:
df.tail(10) # Returns the last 10 rows

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [21]:
df['SepalLengthCm'].head(4) # Returns the first 4 rows from the column SepalLengthCm

0    5.1
1    4.9
2    4.7
3    4.6
Name: SepalLengthCm, dtype: float64

In [25]:
df[['SepalLengthCm', 'Species']] # Returns rows from multiple columns

     SepalLengthCm         Species
0              5.1     Iris-setosa
1              4.9     Iris-setosa
2              4.7     Iris-setosa
3              4.6     Iris-setosa
4              5.0     Iris-setosa
..             ...             ...
145            6.7  Iris-virginica
146            6.3  Iris-virginica
147            6.5  Iris-virginica
148            6.2  Iris-virginica
149            5.9  Iris-virginica

[150 rows x 2 columns]

In [33]:
df.iloc[87] # Returns teh data from row 87

Id                            88
SepalLengthCm                6.3
SepalWidthCm                 2.3
PetalLengthCm                4.4
PetalWidthCm                 1.3
Species          Iris-versicolor
Name: 87, dtype: object

In [37]:
df.iloc[0:10] # Returns data from teh rows 0 to 10

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [43]:
df.iloc[10:20, 3:5] # Returns data from the row 10 to 20 from column 3 and 4 (PetalLengthCm and PetalWidthCm)

    PetalLengthCm  PetalWidthCm
10            1.5           0.2
11            1.6           0.2
12            1.4           0.1
13            1.1           0.1
14            1.2           0.2
15            1.5           0.4
16            1.3           0.4
17            1.4           0.3
18            1.7           0.3
19            1.5           0.3

In [45]:
df.info() # Returns the info of the data Frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [47]:
df.describe() # analyze the stastics for only the numerical columns

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
df.Species.unique() # Returns teh unique values in the Species column of teh DataFrame df

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [20]:
df[df.Species == 'Iris-virginica'] # Only returns the rows where Species is equal to Iris-virginica

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
df[(df.Species == 'Iris-virginica') & (df.PetalLengthCm > 2.0)] # Multiple conditions

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# Function that converts values in a column to date time format  
* pd.to_datetime(df.column_name)
* df['column_name'] = df.column_name.dt.month # chretes a new column for month

# Sorting

In [27]:
df.sort_values(by = 'PetalWidthCm', inplace = True) # sortes ascendingly

In [29]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
32,33,5.2,4.1,1.5,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
...,...,...,...,...,...,...
140,141,6.7,3.1,5.6,2.4,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
100,101,6.3,3.3,6.0,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica

# Data Frame Drop method

In [36]:
df.drop(labels = 'Id', axis = 1, inplace = True) # Dropped the column 'Id'

In [38]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
32             5.2           4.1            1.5           0.1     Iris-setosa
13             4.3           3.0            1.1           0.1     Iris-setosa
37             4.9           3.1            1.5           0.1     Iris-setosa
9              4.9           3.1            1.5           0.1     Iris-setosa
12             4.8           3.0            1.4           0.1     Iris-setosa
..             ...           ...            ...           ...             ...
140            6.7           3.1            5.6           2.4  Iris-virginica
114            5.8           2.8            5.1           2.4  Iris-virginica
144            6.7           3.3            5.7           2.5  Iris-virginica
100            6.3           3.3            6.0           2.5  Iris-virginica
109            7.2           3.6            6.1           2.5  Iris-virginica

[150 rows x 5 columns]

# To drop the NA values from the column

df.dropna(subset = ['column_name']

# Pandas for Analyzing